package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModulePermissionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulePermissionAllPropertiesEquals(ModulePermission expected, ModulePermission actual) {
        assertModulePermissionAutoGeneratedPropertiesEquals(expected, actual);
        assertModulePermissionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulePermissionAllUpdatablePropertiesEquals(ModulePermission expected, ModulePermission actual) {
        assertModulePermissionUpdatableFieldsEquals(expected, actual);
        assertModulePermissionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulePermissionAutoGeneratedPropertiesEquals(ModulePermission expected, ModulePermission actual) {
        assertThat(actual)
            .as("Verify ModulePermission auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulePermissionUpdatableFieldsEquals(ModulePermission expected, ModulePermission actual) {
        assertThat(actual)
            .as("Verify ModulePermission relevant properties")
            .satisfies(a -> assertThat(a.getCanCreate()).as("check canCreate").isEqualTo(expected.getCanCreate()))
            .satisfies(a -> assertThat(a.getCanEdit()).as("check canEdit").isEqualTo(expected.getCanEdit()))
            .satisfies(a -> assertThat(a.getCanDelete()).as("check canDelete").isEqualTo(expected.getCanDelete()))
            .satisfies(a -> assertThat(a.getCanView()).as("check canView").isEqualTo(expected.getCanView()))
            .satisfies(a -> assertThat(a.getCanHistory()).as("check canHistory").isEqualTo(expected.getCanHistory()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulePermissionUpdatableRelationshipsEquals(ModulePermission expected, ModulePermission actual) {
        assertThat(actual)
            .as("Verify ModulePermission relationships")
            .satisfies(a -> assertThat(a.getModule()).as("check module").isEqualTo(expected.getModule()))
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()));
    }
}
