package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModulesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulesAllPropertiesEquals(Modules expected, Modules actual) {
        assertModulesAutoGeneratedPropertiesEquals(expected, actual);
        assertModulesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulesAllUpdatablePropertiesEquals(Modules expected, Modules actual) {
        assertModulesUpdatableFieldsEquals(expected, actual);
        assertModulesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulesAutoGeneratedPropertiesEquals(Modules expected, Modules actual) {
        assertThat(actual)
            .as("Verify Modules auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulesUpdatableFieldsEquals(Modules expected, Modules actual) {
        assertThat(actual)
            .as("Verify Modules relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModulesUpdatableRelationshipsEquals(Modules expected, Modules actual) {
        // empty method
    }
}
